language: scala

scala:
  - "2.11.12"
  - "2.12.11"
  - "2.13.2"

jdk:
  - openjdk11

sudo: required
dist: trusty

env:
  - SCALAJS_VERSION=0.6.32
  - SCALAJS_VERSION=1.0.0

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.coursier
    - $HOME/.sbt

script:
  - sbt ++$TRAVIS_SCALA_VERSION fmtCheck
  - sbt ++$TRAVIS_SCALA_VERSION test mimaReportBinaryIssues

